# Generated by Django 3.2.5 on 2023-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
                ('token', models.CharField(max_length=300, verbose_name='Token')),
            ],
        ),
    ]
